<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Devkit.Server.Application\Devkit.Server.Application.csproj" />
    <ProjectReference Include="..\Devkit.Server.Domain\Devkit.Server.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
