server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log warn;

    location /api/ {
        proxy_pass http://devkit-server:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 25m;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
